export enum PropietarioType {
  PRIMER_REGIDOR = 'PRIMER_REGIDOR',
  SEGUNDO_REGIDOR = 'SEGUNDO_REGIDOR',
  TERCER_REGIDOR = 'TERCER_REGIDOR',
  CUARTO_REGIDOR = 'CUARTO_REGIDOR',
  ALCALDESA = 'ALCALDESA',
  SECRETARIA = 'SECRETARIA',
  SINDICO = 'SINDICO',
}